<?php
// capture the data from the form

use Coco_Solar\Helper;

// phpcs:ignore WordPress.Security.NonceVerification.Missing -- reason
$form_id = absint( $_POST['gform_submit'] ?? Helper::get_gravity_form_id_from_page() );
$form    = \GFAPI::get_form( $form_id );

// retrieve info in the form inserted by the user.

// Step 1
$roof_coords = Helper::capture_coco_map_field_instance( $form, 'map-roof' );

// Step 3
$length_field     = Helper::capture_coco_map_field_instance( $form, 'panel-length' );
$height_field     = Helper::capture_coco_map_field_instance( $form, 'panel-height' );
$panelpower_field = Helper::capture_coco_map_field_instance( $form, 'panel-nominal-power' );
$efficiency_field = Helper::capture_coco_map_field_instance( $form, 'panel-efficiency' );
$quantiles_field  = Helper::capture_coco_map_field_instance( $form, 'panel-quantiles' );
$scenario_label   = '';
$model_field      = Helper::capture_coco_map_field_instance( $form, 'panel-model-dropdown' );
$model_label      = '';
foreach ( $model_field->choices as $choice ) {
	if ( intval( $choice['value'] ) === intval( $model_field->value ) ) {
		$model_label = $choice['text'];
		break;
	}
}
foreach ( $quantiles_field->choices as $choice ) {
	if ( intval( $choice['value'] ) === intval( $quantiles_field->value ) ) {
		$scenario_label = $choice['text'];
		break;
	}
}

// Step 3 generated by the system
$saved_rectangles      = Helper::capture_coco_map_field_instance( $form, 'saved-rectangles' )->value;
$saved_rectangles_data = json_decode( $saved_rectangles, true );
if ( json_last_error() !== JSON_ERROR_NONE ) {
	throw new \Exception( esc_html( 'Error decoding saved rectangles JSON: ' . json_last_error_msg() ) );
}


// retrieve info from the roofs (it's cached), from the solar API.
$coords        = explode( ',', $roof_coords->value );
$building_data = \Coco_Solar\Google_Solar_API::get_solar_building_data( $coords[0], $coords[1] );
$roofs         = $building_data['solarPotential']['roofSegmentStats'] ?? null;

?>

<div class="report-intro">
	<?php
	$total_energy = 0;
	foreach ( $saved_rectangles_data as $saved_rectangle ) {

		$rectangle_power = $saved_rectangle['annualPower'] ?? 0;
		$total_energy   += $rectangle_power;
	}

	echo wp_kses_post( sprintf( __( 'Total Energy Production: <strong><span id="total-energy">%s</span> kWh/year</strong>', 'solar-panel' ), number_format( $total_energy, 0 ) ) );
	?>
</div> <!-- /report-intro -->



<div id="report" class="report-container">
	<h2><?php _e( 'Energy Report', 'solar-project' ); ?></h2>
	<ul>
		<li><b><?php _e( 'Panel Model', 'solar-project' ); ?></b>:
			<?php echo esc_html( $model_label ); ?></li>
		<li><b><?php _e( 'Panel dimensions', 'solar-project' ); ?></b>:
			<?php echo esc_html( $length_field->value ); ?> x <?php echo esc_html( $height_field->value ); ?> mm
		</li>
		<li><b><?php _e( 'Nominal power per panel', 'solar-project' ); ?></b>:
			<?php echo esc_html( $panelpower_field->value ); ?> W</li>
	</ul>

	<?php
	foreach ( $saved_rectangles_data as $i => $saved_rectangle ) :
		// Helper::ddie($saved_rectangle);
		// Helper::ddie($roof);

		$roof            = $roofs[ $saved_rectangle['indexSegment'] ];
		$rectangle_power = $saved_rectangle['annualPower'] ?? 0;
		?>
		<h3><?php printf( __( 'Segment %d', 'solar-panel' ), $i + 1 ); ?> <em><?php echo number_format( $rectangle_power, 0 ); ?> kWh</em> </h3>
		<p>
			<?php printf( __( 'Pitch: %1$d°, Orientation: %2$s, Area: %3$d m²', 'solar-panel' ), $roof['pitchDegrees'], esc_html( $saved_rectangle['orientation'] ), $saved_rectangle['panelsSurface'] ); ?>
		</p>
		<table class="table">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Hours sun / year', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Panels', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Power per Panel', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'System Efficiency', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Annual Energy (kWh)', 'solar-panel' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<?php
					$hours_sun = number_format( $roof['stats']['sunshineQuantiles'][ $quantiles_field->value ], 1 );
					?>
					<td><?php echo esc_html( $hours_sun ); ?> h</td>
					<td><?php echo esc_html( $saved_rectangle['numberPanels'] ); ?></td>
					<td><?php echo esc_html( $panelpower_field->value ); ?> W</td>
					<td><?php echo esc_html( $efficiency_field->value * 100 ); ?> %</td>
					<td><b><?php echo number_format( $rectangle_power, 0 ); ?> kWh </b></td>
				</tr>
			</tbody>
		</table>

	<?php endforeach; ?>
</div>



<?php
