<?php
// capture the data from the form

use Coco_Solar\Helper;

$form_id = $_POST['gform_submit'] ?? Helper::get_gravity_form_id_from_page();
$form    = \GFAPI::get_form( $form_id );

// retrieve info in the form inserted by the user.

// Step 1
$roof_coords = Helper::capture_coco_map_field_instance( $form, 'map-roof' );

// Step 3
$length_field     = Helper::capture_coco_map_field_instance( $form, 'panel-length' );
$height_field     = Helper::capture_coco_map_field_instance( $form, 'panel-height' );
$panelpower_field = Helper::capture_coco_map_field_instance( $form, 'panel-nominal-power' );
$efficiency_field = Helper::capture_coco_map_field_instance( $form, 'panel-efficiency' );
$quantiles_field  = Helper::capture_coco_map_field_instance( $form, 'panel-quantiles' );
$scenario_label   = '';
$model_field      = Helper::capture_coco_map_field_instance( $form, 'panel-model-dropdown' );
$model_label      = '';
foreach ( $model_field->choices as $choice ) {
	if ( intval( $choice['value'] ) === intval( $model_field->value ) ) {
		$model_label = $choice['text'];
		break;
	}
}
foreach ( $quantiles_field->choices as $choice ) {
	if ( intval( $choice['value'] ) === intval( $quantiles_field->value ) ) {
		$scenario_label = $choice['text'];
		break;
	}
}

// Step 3 generated by the system
$saved_rectangles = Helper::capture_coco_map_field_instance( $form, 'saved-rectangles' )->value;
$saved_rectangles_data = json_decode( $saved_rectangles, true );
if ( json_last_error() !== JSON_ERROR_NONE ) {
	throw new \Exception( 'Error decoding saved rectangles JSON: ' . json_last_error_msg() );
}


// retrieve info from the roofs (it's cached), from the solar API.
$coords        = explode( ',', $roof_coords->value );
$building_data = \Coco_Solar\Google_Solar_API::get_solar_building_data( $coords[0], $coords[1] );
$roofs         = $building_data['solarPotential']['roofSegmentStats'] ?? null;

?>

<div class="report-intro">
	<?php
	// Helper::ddie($quantiles_field);
	$total_energy = 0;
	foreach ( $saved_rectangles_data as $saved_rectangle ) {
		// Helper::ddie($saved_rectangle);
		// Helper::ddie($roof);

		$roof = $roofs[$saved_rectangle['indexSegment']];

		// Calculate Energy:
		$number_panels = intval( $saved_rectangle['numberPanels'] ?? 0 );
		$panel_power   = intval( $panelpower_field->value );

		$hours_sun        = intval( $roof['stats']['sunshineQuantiles'][$quantiles_field->value] );
		$final_efficiency = floatval($efficiency_field->value);

		$roof_energy = Model_Panel::calculate_power_energy( [
			'number_panels'    => $number_panels,
			'panel_power'      => $panel_power,
			'hours_sun'        => $hours_sun,
			'final_efficiency' => $final_efficiency
		] );
		$total_energy += $roof_energy;
	}

	printf( __( 'Total Energy Production: <strong>%s kWh/year</strong>', 'solar-panel' ), number_format( $total_energy, 2 ) );
	?>
</div> <!-- /report-intro -->



<div id="report" class="report-container">
	<h2><?php _e( 'Energy Report', 'solar-project' ); ?></h2>

	<?php
	foreach ( $saved_rectangles_data as $i => $saved_rectangle ) :
		// Helper::ddie($saved_rectangle);
		// Helper::ddie($roof);

		$roof = $roofs[$saved_rectangle['indexSegment']];
	?>
		<h3><?php printf( __( 'Segment %d', 'solar-panel' ), $i + 1 ); ?></h3>
		<p>
			<?php printf( __( 'Pitch: %1$d°, Orientation: %2$s, Area: %3$d m²', 'solar-panel' ), $roof['pitchDegrees'], esc_html( $saved_rectangle['orientation'] ), $roof['stats']['areaMeters2'] ); ?>
		</p>
		<table class="table">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Segment', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Panels', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Model', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Power per Panel', 'solar-panel' ); ?></th>
					<th><?php esc_html_e( 'Annual Energy (kWh)', 'solar-panel' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?php echo esc_html( $i + 1 ); ?></td>
					<td><?php echo esc_html( $saved_rectangle['numberPanels'] ); ?></td>
					<td><?php echo esc_html( $model_label ); ?></td>
					<td><?php echo esc_html( $panelpower_field->value ); ?> W</td>
					<?php
					$roof_energy = Model_Panel::calculate_power_energy( [
						'number_panels' => intval( $saved_rectangle['numberPanels'] ),
						'panel_power' => $panelpower_field->value,
						'hours_sun' => intval( $roof['stats']['sunshineQuantiles'][$quantiles_field->value] ),
						'final_efficiency' => floatval($efficiency_field->value)
					] );
					?>
					<td><?php echo number_format( $roof_energy, 2 ); ?> kWh</td>
				</tr>
			</tbody>
		</table>
		<p>
			<strong>
				<?php printf( __( 'Total Energy for segment %1$s: %2$s kWh/year', 'solar-panel' ), esc_html( $i ), number_format( $roof_energy, 2 ) ); ?>
			</strong>
		</p>
	<?php endforeach; ?>
</div>



<?php
